### ISSUE TITLE
뭔데 이거

### ISSUE THREAD

**Issue by jwvg0425** [pjc02478/lemon#2]
나 왜 콜라보레이터로 추가함? 내 맘대로 커밋해도 됨?

**Comment by pjc0247** [comment]
ㄷㄷ 갓현욱님의커밋

커밋한개할때마다 돈줘야될듯 ㄷ

**Comment by jwvg0425** [comment]
커밋 하나당 천원씩만 주셈 앞으로 하루에 커밋 100개씩 해야지
